// Torsion TorqueScript IDE - Copyright (C) Sickhead Games, LLC
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Generated by DialogBlocks (unregistered), 09/22/05 13:31:37

#ifndef _BREAKPOINTSPANEL_H_
#define _BREAKPOINTSPANEL_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "BreakpointsPanel.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/toolbar.h"
#include "wx/listctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class tsToolBar;
class wxListCtrl;
////@end forward declarations

class BreakpointEvent;
class Breakpoint;
class BreakpointArray;

/*!
 * Control identifiers
 */

////@begin control identifiers
#define SYMBOL_BREAKPOINTSPANEL_STYLE wxCLIP_CHILDREN
#define SYMBOL_BREAKPOINTSPANEL_TITLE _("Breakpoints")
#define SYMBOL_BREAKPOINTSPANEL_IDNAME wxID_ANY
#define SYMBOL_BREAKPOINTSPANEL_SIZE wxDefaultSize
#define SYMBOL_BREAKPOINTSPANEL_POSITION wxDefaultPosition
#define bpID_BREAKPOINTLIST 10003
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

/*!
 * BreakpointsPanel class declaration
 */

class BreakpointsPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( BreakpointsPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    BreakpointsPanel( );
    BreakpointsPanel( wxWindow* parent, wxWindowID id = SYMBOL_BREAKPOINTSPANEL_IDNAME, const wxPoint& pos = SYMBOL_BREAKPOINTSPANEL_POSITION, const wxSize& size = SYMBOL_BREAKPOINTSPANEL_SIZE, long style = SYMBOL_BREAKPOINTSPANEL_STYLE );
   ~BreakpointsPanel();

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_BREAKPOINTSPANEL_IDNAME, const wxPoint& pos = SYMBOL_BREAKPOINTSPANEL_POSITION, const wxSize& size = SYMBOL_BREAKPOINTSPANEL_SIZE, long style = SYMBOL_BREAKPOINTSPANEL_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin BreakpointsPanel event handler declarations

   /// wxEVT_COMMAND_LIST_ITEM_ACTIVATED event handler for bpID_BREAKPOINTLIST
   void OnBreakpointActivated( wxListEvent& event );

////@end BreakpointsPanel event handler declarations

   void OnToggle( wxCommandEvent& event );
   void OnDelete( wxCommandEvent& event );
   void OnProperties( wxCommandEvent& event );
   void OnGotoSource( wxCommandEvent& event );
   void OnUpdateUI( wxUpdateUIEvent& event );
   void OnUpdateToggleUI( wxUpdateUIEvent& event );
   void OnUpdateSingleUI( wxUpdateUIEvent& event );
   void OnBreakpointEvent( BreakpointEvent& event );

   void OnKeyDown( wxListEvent& event );

////@begin BreakpointsPanel member function declarations

   /// Retrieves bitmap resources
   wxBitmap GetBitmapResource( const wxString& name );

   /// Retrieves icon resources
   wxIcon GetIconResource( const wxString& name );
////@end BreakpointsPanel member function declarations

    void UpdateBreakpoints();
   void AddBreakpoint( Breakpoint* bp );
   void UpdateBreakpoint( long item, Breakpoint* bp );
   int GetSelected( BreakpointArray& selected );
   virtual bool ProcessEvent( wxEvent& event );

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin BreakpointsPanel member variables
   tsToolBar* m_Toolbar;
   wxListCtrl* m_BreakList;
////@end BreakpointsPanel member variables

    wxImageList*  m_Icons;
};

#endif
    // _BREAKPOINTSPANEL_H_
