// Torsion TorqueScript IDE - Copyright (C) Sickhead Games, LLC
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Generated by DialogBlocks (unregistered), 31/01/2006 21:22:37

#ifndef _PROJECTDLG_H_
#define _PROJECTDLG_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "ProjectDlg.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
#include "wx/propgrid/manager.h"
////@end includes

#include "ProjectDoc.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxPropertyGridManager;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define SYMBOL_PROJECTDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_PROJECTDLG_TITLE _("Project Settings")
#define SYMBOL_PROJECTDLG_IDNAME wxID_ANY
#define SYMBOL_PROJECTDLG_SIZE wxSize(425, 435)
#define SYMBOL_PROJECTDLG_POSITION wxDefaultPosition
#define ID_NOTEBOOK 10019
#define pdID_CONFIGLIST 10007
#define pdID_EDIT 10000
#define pdID_NEW 10001
#define pdID_DELETE 10002
#define pdID_COPY 10004
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * ProjectDlg class declaration
 */

class ProjectDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ProjectDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ProjectDlg( );
    ProjectDlg( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTDLG_POSITION, const wxSize& size = SYMBOL_PROJECTDLG_SIZE, long style = SYMBOL_PROJECTDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTDLG_POSITION, const wxSize& size = SYMBOL_PROJECTDLG_SIZE, long style = SYMBOL_PROJECTDLG_STYLE );

    int ShowModal( ProjectDoc* projectDoc );

   bool GetRebuildExports() const { return m_RebuildExports; }

protected:

    /// Creates the controls and sizers
    void CreateControls();

   void UpdateConfigList();


////@begin ProjectDlg event handler declarations

   /// wxEVT_COMMAND_LISTBOX_DOUBLECLICKED event handler for pdID_CONFIGLIST
   void OnConfigDoubleClicked( wxCommandEvent& event );

   /// wxEVT_COMMAND_BUTTON_CLICKED event handler for pdID_EDIT
   void OnEditClick( wxCommandEvent& event );

   /// wxEVT_UPDATE_UI event handler for pdID_EDIT
   void OnConfigSelUpdate( wxUpdateUIEvent& event );

   /// wxEVT_COMMAND_BUTTON_CLICKED event handler for pdID_NEW
   void OnNewClick( wxCommandEvent& event );

   /// wxEVT_COMMAND_BUTTON_CLICKED event handler for pdID_DELETE
   void OnDeleteClick( wxCommandEvent& event );

   /// wxEVT_COMMAND_BUTTON_CLICKED event handler for pdID_COPY
   void OnCopyClick( wxCommandEvent& event );

   /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
   void OnOkClick( wxCommandEvent& event );

////@end ProjectDlg event handler declarations

////@begin ProjectDlg member function declarations

   /// Retrieves bitmap resources
   wxBitmap GetBitmapResource( const wxString& name );

   /// Retrieves icon resources
   wxIcon GetIconResource( const wxString& name );
////@end ProjectDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ProjectDlg member variables
   wxPropertyGridManager* m_PropGrid;
   wxListBox* m_ConfigList;
////@end ProjectDlg member variables

   ProjectDoc*          m_Project;
   ProjectConfigArray   m_Configs;
   bool                 m_ConfigModified;
   bool                 m_RebuildExports;
};

#endif
    // _PROJECTDLG_H_
