// Torsion TorqueScript IDE - Copyright (C) Sickhead Games, LLC
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Generated by DialogBlocks (unregistered), 09/20/05 23:54:14

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma implementation "ReloadFile.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "ReloadFile.h"

////@begin XPM images
////@end XPM images

/*!
 * ReloadFileDlg type definition
 */

IMPLEMENT_DYNAMIC_CLASS( ReloadFileDlg, wxDialog )

/*!
 * ReloadFileDlg event table definition
 */

BEGIN_EVENT_TABLE( ReloadFileDlg, wxDialog )

////@begin ReloadFileDlg event table entries
    EVT_BUTTON( wxID_YES, ReloadFileDlg::OnButtonClick )

    EVT_BUTTON( wxID_YESTOALL, ReloadFileDlg::OnButtonClick )

    EVT_BUTTON( wxID_NO, ReloadFileDlg::OnButtonClick )

    EVT_BUTTON( wxID_NOTOALL, ReloadFileDlg::OnButtonClick )

////@end ReloadFileDlg event table entries

END_EVENT_TABLE()

/*!
 * ReloadFileDlg constructors
 */

ReloadFileDlg::ReloadFileDlg( )
{
}

ReloadFileDlg::ReloadFileDlg( wxWindow* parent, const wxString& FilePath )
{
    Create(parent, FilePath);
}

/*!
 * ReloadFileDlg creator
 */

bool ReloadFileDlg::Create( wxWindow* parent, const wxString& FilePath )
{
    m_FilePath = FilePath;

////@begin ReloadFileDlg member initialisation
////@end ReloadFileDlg member initialisation

////@begin ReloadFileDlg creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, wxID_ANY, 
       SYMBOL_RELOADFILEDLG_TITLE, 
       SYMBOL_RELOADFILEDLG_POSITION, 
       SYMBOL_RELOADFILEDLG_SIZE, 
       SYMBOL_RELOADFILEDLG_STYLE );

    CreateControls();
    GetSizer()->Fit(this);
    GetSizer()->SetSizeHints(this);
    Centre();
////@end ReloadFileDlg creation
    return TRUE;
}

/*!
 * Control creation for ReloadFileDlg
 */

void ReloadFileDlg::CreateControls()
{    
////@begin ReloadFileDlg content construction
    // Generated by DialogBlocks, 09/22/05 13:19:29 (unregistered)

    ReloadFileDlg* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
    itemBoxSizer2->Add(itemBoxSizer3, 0, wxALIGN_CENTER_VERTICAL|wxALL, 7);

    wxStaticText* itemStaticText4 = new wxStaticText( itemDialog1, wxID_FILE, m_FilePath, wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer3->Add(itemStaticText4, 0, wxALIGN_LEFT|wxALL, 5);

    wxStaticText* itemStaticText5 = new wxStaticText( itemDialog1, wxID_STATIC, _("This file has been modified outside of Torsion.\nDo you want to reload it?"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer3->Add(itemStaticText5, 0, wxALIGN_CENTER_HORIZONTAL|wxTOP|wxBOTTOM, 20);

    wxBoxSizer* itemBoxSizer6 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer6, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 0);

    itemBoxSizer6->Add(20, 5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton8 = new wxButton( itemDialog1, wxID_YES, _("&Yes"), wxDefaultPosition, wxDefaultSize, 0 );
    itemButton8->SetDefault();
    itemBoxSizer6->Add(itemButton8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 3);

    wxButton* itemButton9 = new wxButton( itemDialog1, wxID_YESTOALL, _("Yes to &All"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer6->Add(itemButton9, 0, wxALIGN_CENTER_VERTICAL|wxALL, 3);

    wxButton* itemButton10 = new wxButton( itemDialog1, wxID_NO, _("&No"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer6->Add(itemButton10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 3);

    wxButton* itemButton11 = new wxButton( itemDialog1, wxID_NOTOALL, _("No to A&ll"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer6->Add(itemButton11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 3);

    itemBoxSizer6->Add(20, 5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end ReloadFileDlg content construction
}

/*!
 * Should we show tooltips?
 */

bool ReloadFileDlg::ShowToolTips()
{
    return TRUE;
}

/*!
 * Get bitmap resources
 */

wxBitmap ReloadFileDlg::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin ReloadFileDlg bitmap retrieval
    return wxNullBitmap;
////@end ReloadFileDlg bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon ReloadFileDlg::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin ReloadFileDlg icon retrieval
    return wxNullIcon;
////@end ReloadFileDlg icon retrieval
}

void ReloadFileDlg::OnButtonClick( wxCommandEvent& event )
{
   return EndModal( event.GetId() );
}



