// Torsion TorqueScript IDE - Copyright (C) Sickhead Games, LLC
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Generated by DialogBlocks (unregistered), 09/20/05 23:54:14

#ifndef _RELOADFILE_H_
#define _RELOADFILE_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "ReloadFile.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10006
#define SYMBOL_RELOADFILEDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_RELOADFILEDLG_TITLE _("Torsion")
#define SYMBOL_RELOADFILEDLG_IDNAME ID_DIALOG
#define SYMBOL_RELOADFILEDLG_SIZE wxSize(400, 300)
#define SYMBOL_RELOADFILEDLG_POSITION wxDefaultPosition
#define wxID_FILE 10000
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

/*!
 * ReloadFileDlg class declaration
 */

class ReloadFileDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ReloadFileDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ReloadFileDlg( );
    ReloadFileDlg( wxWindow* parent, const wxString& FilePath );

    /// Creation
    bool Create( wxWindow* parent, const wxString& FilePath );

    /// Creates the controls and sizers
    void CreateControls();

////@begin ReloadFileDlg event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_YES
    void OnButtonClick( wxCommandEvent& event );

////@end ReloadFileDlg event handler declarations

////@begin ReloadFileDlg member function declarations

    wxString GetFilePath() const { return m_FilePath ; }
    void SetFilePath(wxString value) { m_FilePath = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ReloadFileDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ReloadFileDlg member variables
    wxString m_FilePath;
////@end ReloadFileDlg member variables
};

#endif
    // _RELOADFILE_H_
